server:
  port: 8082

spring:
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}

consumer:
  pool:
    core-pool-size: ${CORE_POOL_SIZE:3}
    max-pool-size: ${POOL_MAX_SIZE:8}
    queue-capacity: 100
    keep-alive-seconds: 60

app:
  handler:
    base-url: ${APP_HANDLER_PATH:http://localhost:8081/api}