server:
  port: 8081

spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}
      auto-index-creation: true
  activemq:
    broker-url: ${ACTIVEMQ_BROKER_URL:tcp://localhost:61616}
    user: ${ACTIVEMQ_USER:admin}
    password: ${ACTIVEMQ_PASSWORD:admin}

youtube:
  api:
    base-url: https://youtube.googleapis.com/youtube/v3/commentThreads
    search-url: https://youtube.googleapis.com/youtube/v3/search
    videos-url: https://youtube.googleapis.com/youtube/v3/videos
    key: ${YOUTUBE_API_KEY}

jms:
  queues:
    analysis-request: sentiment.analysis.request
    analysis-response: sentiment.analysis.response